// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/review_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/review_service.go -destination=internal/service/mock/mock_review_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "english-learner/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReviewService is a mock of ReviewService interface.
type MockReviewService struct {
	ctrl     *gomock.Controller
	recorder *MockReviewServiceMockRecorder
	isgomock struct{}
}

// MockReviewServiceMockRecorder is the mock recorder for MockReviewService.
type MockReviewServiceMockRecorder struct {
	mock *MockReviewService
}

// NewMockReviewService creates a new mock instance.
func NewMockReviewService(ctrl *gomock.Controller) *MockReviewService {
	mock := &MockReviewService{ctrl: ctrl}
	mock.recorder = &MockReviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewService) EXPECT() *MockReviewServiceMockRecorder {
	return m.recorder
}

// CalcWordStats mocks base method.
func (m *MockReviewService) CalcWordStats(wordID string) (*domain.WordStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalcWordStats", wordID)
	ret0, _ := ret[0].(*domain.WordStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalcWordStats indicates an expected call of CalcWordStats.
func (mr *MockReviewServiceMockRecorder) CalcWordStats(wordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalcWordStats", reflect.TypeOf((*MockReviewService)(nil).CalcWordStats), wordID)
}

// GetReviewWords mocks base method.
func (m *MockReviewService) GetReviewWords(date string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewWords", date)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewWords indicates an expected call of GetReviewWords.
func (mr *MockReviewServiceMockRecorder) GetReviewWords(date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewWords", reflect.TypeOf((*MockReviewService)(nil).GetReviewWords), date)
}
