// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/plan_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/plan_service.go -destination=internal/service/mock/mock_plan_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "english-learner/internal/domain"
	service "english-learner/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlanService is a mock of PlanService interface.
type MockPlanService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanServiceMockRecorder
	isgomock struct{}
}

// MockPlanServiceMockRecorder is the mock recorder for MockPlanService.
type MockPlanServiceMockRecorder struct {
	mock *MockPlanService
}

// NewMockPlanService creates a new mock instance.
func NewMockPlanService(ctrl *gomock.Controller) *MockPlanService {
	mock := &MockPlanService{ctrl: ctrl}
	mock.recorder = &MockPlanServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanService) EXPECT() *MockPlanServiceMockRecorder {
	return m.recorder
}

// GetOverview mocks base method.
func (m *MockPlanService) GetOverview() (*domain.StudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverview")
	ret0, _ := ret[0].(*domain.StudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverview indicates an expected call of GetOverview.
func (mr *MockPlanServiceMockRecorder) GetOverview() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverview", reflect.TypeOf((*MockPlanService)(nil).GetOverview))
}

// GetTodayPlan mocks base method.
func (m *MockPlanService) GetTodayPlan() (*service.TodayPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayPlan")
	ret0, _ := ret[0].(*service.TodayPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayPlan indicates an expected call of GetTodayPlan.
func (mr *MockPlanServiceMockRecorder) GetTodayPlan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayPlan", reflect.TypeOf((*MockPlanService)(nil).GetTodayPlan))
}

// HasPlan mocks base method.
func (m *MockPlanService) HasPlan() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPlan")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPlan indicates an expected call of HasPlan.
func (mr *MockPlanServiceMockRecorder) HasPlan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPlan", reflect.TypeOf((*MockPlanService)(nil).HasPlan))
}

// InitPlan mocks base method.
func (m *MockPlanService) InitPlan(libraryID string) (*domain.StudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPlan", libraryID)
	ret0, _ := ret[0].(*domain.StudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitPlan indicates an expected call of InitPlan.
func (mr *MockPlanServiceMockRecorder) InitPlan(libraryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPlan", reflect.TypeOf((*MockPlanService)(nil).InitPlan), libraryID)
}
