// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/library_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/library_repo.go -destination=internal/repository/mock/mock_library_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "english-learner/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLibraryRepository is a mock of LibraryRepository interface.
type MockLibraryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryRepositoryMockRecorder
	isgomock struct{}
}

// MockLibraryRepositoryMockRecorder is the mock recorder for MockLibraryRepository.
type MockLibraryRepositoryMockRecorder struct {
	mock *MockLibraryRepository
}

// NewMockLibraryRepository creates a new mock instance.
func NewMockLibraryRepository(ctrl *gomock.Controller) *MockLibraryRepository {
	mock := &MockLibraryRepository{ctrl: ctrl}
	mock.recorder = &MockLibraryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibraryRepository) EXPECT() *MockLibraryRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockLibraryRepository) GetAll() ([]*domain.WordLibrary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*domain.WordLibrary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLibraryRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLibraryRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockLibraryRepository) GetByID(id string) (*domain.WordLibrary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.WordLibrary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLibraryRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLibraryRepository)(nil).GetByID), id)
}

// Reload mocks base method.
func (m *MockLibraryRepository) Reload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockLibraryRepositoryMockRecorder) Reload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockLibraryRepository)(nil).Reload))
}
