// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/plan_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/plan_repo.go -destination=internal/repository/mock/mock_plan_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "english-learner/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPlanRepository) Get() (*domain.StudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*domain.StudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPlanRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPlanRepository)(nil).Get))
}

// Save mocks base method.
func (m *MockPlanRepository) Save(plan *domain.StudyPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPlanRepositoryMockRecorder) Save(plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPlanRepository)(nil).Save), plan)
}

// UpdateDayReviewWords mocks base method.
func (m *MockPlanRepository) UpdateDayReviewWords(day int, wordIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDayReviewWords", day, wordIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDayReviewWords indicates an expected call of UpdateDayReviewWords.
func (mr *MockPlanRepositoryMockRecorder) UpdateDayReviewWords(day, wordIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDayReviewWords", reflect.TypeOf((*MockPlanRepository)(nil).UpdateDayReviewWords), day, wordIDs)
}

// UpdateDayStatus mocks base method.
func (m *MockPlanRepository) UpdateDayStatus(day int, status domain.PlanStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDayStatus", day, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDayStatus indicates an expected call of UpdateDayStatus.
func (mr *MockPlanRepositoryMockRecorder) UpdateDayStatus(day, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDayStatus", reflect.TypeOf((*MockPlanRepository)(nil).UpdateDayStatus), day, status)
}
