// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/record_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/record_repo.go -destination=internal/repository/mock/mock_record_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "english-learner/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRecordRepository) Add(record *domain.LearningRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRecordRepositoryMockRecorder) Add(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRecordRepository)(nil).Add), record)
}

// GetAll mocks base method.
func (m *MockRecordRepository) GetAll() ([]*domain.LearningRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*domain.LearningRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRecordRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRecordRepository)(nil).GetAll))
}

// GetByDate mocks base method.
func (m *MockRecordRepository) GetByDate(date string) ([]*domain.LearningRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDate", date)
	ret0, _ := ret[0].([]*domain.LearningRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDate indicates an expected call of GetByDate.
func (mr *MockRecordRepositoryMockRecorder) GetByDate(date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDate", reflect.TypeOf((*MockRecordRepository)(nil).GetByDate), date)
}

// GetByWordID mocks base method.
func (m *MockRecordRepository) GetByWordID(wordID string) ([]*domain.LearningRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWordID", wordID)
	ret0, _ := ret[0].([]*domain.LearningRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWordID indicates an expected call of GetByWordID.
func (mr *MockRecordRepositoryMockRecorder) GetByWordID(wordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWordID", reflect.TypeOf((*MockRecordRepository)(nil).GetByWordID), wordID)
}

// MockCheckInRepository is a mock of CheckInRepository interface.
type MockCheckInRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckInRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckInRepositoryMockRecorder is the mock recorder for MockCheckInRepository.
type MockCheckInRepositoryMockRecorder struct {
	mock *MockCheckInRepository
}

// NewMockCheckInRepository creates a new mock instance.
func NewMockCheckInRepository(ctrl *gomock.Controller) *MockCheckInRepository {
	mock := &MockCheckInRepository{ctrl: ctrl}
	mock.recorder = &MockCheckInRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckInRepository) EXPECT() *MockCheckInRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCheckInRepository) Add(checkIn *domain.CheckIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", checkIn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCheckInRepositoryMockRecorder) Add(checkIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCheckInRepository)(nil).Add), checkIn)
}

// Exists mocks base method.
func (m *MockCheckInRepository) Exists(day int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", day)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCheckInRepositoryMockRecorder) Exists(day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCheckInRepository)(nil).Exists), day)
}

// GetAll mocks base method.
func (m *MockCheckInRepository) GetAll() ([]*domain.CheckIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*domain.CheckIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCheckInRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCheckInRepository)(nil).GetAll))
}

// GetByDay mocks base method.
func (m *MockCheckInRepository) GetByDay(day int) (*domain.CheckIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDay", day)
	ret0, _ := ret[0].(*domain.CheckIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDay indicates an expected call of GetByDay.
func (mr *MockCheckInRepositoryMockRecorder) GetByDay(day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDay", reflect.TypeOf((*MockCheckInRepository)(nil).GetByDay), day)
}
